### PR TITLE
Add authentication with intra login and repo, browse command

### PR DESCRIPTION
**Pull request by tkomatsu**
I have added 3 features. One is the user authentication feature. The other is subcommand to clone repository. The last is subcommand to open project page in web browser.

## User Authentication

Users can authenticate themselves by adding a redirect URI to the configuration file. The obtained token is saved in the configuration file so that the login information is retained continuously. The user only has to set it up the first time, and goft will automatically update it after that. Config file is now stored in `~/.config/goft/config.yml`. I think it is easier for users to understand it is saved in the same location as other programs like GitHub CLI.

```bash
$ goft auth login
Logged in as tkomatsu
$ goft auth logout
Logged out
$
```

You need to call `saveConfig()` inside each command in order to save the token after the execution of the command.

```go
cobra.Command{
	Use:   "foo",
	Short: "You need to call saveConfig()",
	RunE: func(cmd *cobra.Command, args []string) error {
		defer saveConfig()
		// ... execute command
	}
}
```

You can also do requests to endpoints such as `/me` after authentication.

## repo Command

I have added `list`, `clone`, and `path` as subcommands of `repo`. I also added the API endpoint for them.

### list

`list` command can display a list of repositories stored in the 42 intra. The maximum number of repositories to display can be set as an option, and the default value is 5.

```bash
$ goft repo list -h
Show team locked project list

Usage:
  goft repo list [flags]

Flags:
  -h, --help        help for list
  -L, --limit int   Maximum number of repositories to list (default 5)

Global Flags:
      --config string   config file (default is $HOME/.config/goft/secret.yml)
$ goft repo list
old-cpp-module-00
ft_containers
ft_communication_v2
refactor_bsq
go-piscine-go-00
$
```

### clone

`clone` command takes a slug as first argument and clones the latest repository for the project. You can additionally pass the target directory of the clone as second argument.

```bash
$ goft repo clone ft_containers
Cloning into 'ft_containers'...
remote: Enumerating objects: 965, done.
remote: Counting objects: 100% (965/965), done.
remote: Compressing objects: 100% (307/307), done.
remote: Total 965 (delta 655), reused 936 (delta 641)
Receiving objects: 100% (965/965), 143.47 KiB | 4.48 MiB/s, done.
Resolving deltas: 100% (655/655), done.
$ goft repo clone ft_containers targetdir
Cloning into 'targetdir'...
remote: Enumerating objects: 965, done.
remote: Counting objects: 100% (965/965), done.
remote: Compressing objects: 100% (307/307), done.
remote: Total 965 (delta 655), reused 936 (delta 641)
Receiving objects: 100% (965/965), 143.47 KiB | 4.35 MiB/s, done.
Resolving deltas: 100% (655/655), done.
$ ls
ft_containers			targetdir
$
```

### path

`path` command takes slug as an argument and outputs the path to the latest repository for the issue to the standard output. This command is to use when you want to add a remote repository to an existing local repository like this.

```bash
$ git remote -v
origin	git@github.com:tkomatsu/ft_containers.git (fetch)
origin	git@github.com:tkomatsu/ft_containers.git (push)
$ goft repo path ft_containers
git@vogsphere-v2.42tokyo.jp:vogsphere/intra-uuid-4cb9e09e-d06b-49dc-adaa-d8cefe3e7005-3576881
$ git remote add intra `goft repo path ft_containers`
$ git remote -v
intra	git@vogsphere-v2.42tokyo.jp:vogsphere/intra-uuid-4cb9e09e-d06b-49dc-adaa-d8cefe3e7005-3576881 (fetch)
intra	git@vogsphere-v2.42tokyo.jp:vogsphere/intra-uuid-4cb9e09e-d06b-49dc-adaa-d8cefe3e7005-3576881 (push)
origin	git@github.com:tkomatsu/ft_containers.git (fetch)
origin	git@github.com:tkomatsu/ft_containers.git (push)
$
```
## browse Command

`browse` command takes slug as an argument and open user project page in web browser.

```go
$ goft browse webserv
$ goft browse c-piscine-c-00
```

## Format

`golint` is deprecated (https://github.com/golang/go/issues/38968). I use [goimports](https://pkg.go.dev/golang.org/x/tools/cmd/goimports) for format. The files I made changes to has been applied.

### CODE REVIEW

**Comment by tkomatsu** [comment]
Finally, I've fixed. Please check Pull Request🙏

**Comment by mehdibo** [comment]
Hello Tatsuhiro!
Really appreciate your contribution

Is it possible to separate these into different PRs please? (Check [CONTRIBUTING.md](https://github.com/mehdibo/goft/blob/develop/CONTRIBUTING.md))

## User authentication
Why would you want to authenticate a user? any specific usage you have in mind?

I agree with the config file's location part, it is better to follow the standard as you said.

## Repo command
It looks like you had in mind a student will use this to list his repos, but my purpose of Goft is to make it easy for staff members to interact with the API, so our use case would be to list repos of a specific student (passed as an argument) rather than a login from the config file

### list
How do you see this command used? I think the path command is enough, or maybe combine list and path into one command that outputs the project details and the repo's path?

### clone 
In my opinion, it is simpler to use the `path` command and manually `git clone` the repository rather than add code to Goft that does that.

## path
Check comment on list

## Browse command
How do you see this command used too? Don't you think it is simpler to use the intranet to open a link?

## Format
You are right, I should stop using golint

**Comment by tkomatsu** [comment]
Thank you for checking PR!
> Is it possible to separate these into different PRs please? (Check CONTRIBUTING.md)

I'll do it.

**Comment by tkomatsu** [comment]
I've separated this PR so I'll close this PR.

**Pull request closed without merging**
