### PR TITLE
Feature: add authentication

### PR DESCRIPTION
**Pull request by tkomatsu**
## User Authentication

Users can authenticate themselves by adding a redirect URI to the configuration file. The obtained token is saved in the configuration file so that the login information is retained continuously. The user only has to set it up the first time, and goft will automatically update it after that. Config file is now stored in `~/.config/goft/config.yml`. I think it is easier for users to understand it is saved in the same location as other programs like GitHub CLI.

```bash
$ goft auth login
Logged in as tkomatsu
$ goft auth logout
Logged out
$
```

You need to call `saveConfig()` inside each command in order to save the token after the execution of the command.

```go
cobra.Command{
	Use:   "foo",
	Short: "You need to call saveConfig()",
	RunE: func(cmd *cobra.Command, args []string) error {
		defer saveConfig()
		// ... execute command
	}
}
```

### CODE REVIEW

**Comment by tkomatsu** [comment]
> Why would you want to authenticate a user? any specific usage you have in mind?
> I agree with the config file's location part, it is better to follow the standard as you said.

Initially, I was aiming to get user information from the /me endpoint. From that information, I aimed to get the information of the registered project and the repository.
However, we can get the same information from /users/<login> so it seems that we no longer need authentication.

I thought user authentication makes it enable to submit project from API. I did'nt know student cannot use POST method😢

**Comment by mehdibo** [comment]
I see, I don't think we'll need the auth either, but a caching system for tokens (outside the config file) would be really good because currently if you run Goft in a loop inside a bash script for example, it will fetch a new token everytime.

caching is a good to have

**Comment by tkomatsu** [comment]
Do you think it is good for goft having `auth` command? I don't think so.
If you agree with me, I will close this PR.

If you think it's good, I will fix cashing system.

**Comment by mehdibo** [comment]
I don't think we will need the `auth` command for goft

**Pull request closed without merging**
